package com.accp.myoa.entity;

// default package
// Generated 2016-4-17 16:46:20 by Hibernate Tools 4.3.1.Final

/**
 * Goods generated by hbm2java
 */
public class Goods implements java.io.Serializable {

    private Integer id;
    private String  name;
    private String  price;
    private Integer count;
    private String  type;
    private String  steamId;
    private String  iconBase64;

    public Goods() {
    }

    public Goods(String name, String price, Integer count, String type, String steamId,
                 String iconBase64) {
        this.name = name;
        this.price = price;
        this.count = count;
        this.type = type;
        this.steamId = steamId;
        this.iconBase64 = iconBase64;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Integer getCount() {
        return this.count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSteamId() {
        return this.steamId;
    }

    public void setSteamId(String steamId) {
        this.steamId = steamId;
    }

    public String getIconBase64() {
        return this.iconBase64;
    }

    public void setIconBase64(String iconBase64) {
        this.iconBase64 = iconBase64;
    }

}
