package com.accp.myoa.entity;

// default package
// Generated 2016-4-29 17:40:58 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Goods generated by hbm2java
 */
public class Goods implements java.io.Serializable {

    private Integer id;
    private String  name;
    private String  price;
    private String  iconBase64;
    private String  classid;
    private String  imgurl;
    private String  instanceId;
    private String  type;
    private String  nameColor;
    private Date    lastupdatetime;
    

    public Goods() {
    }

    public Goods(String name, String price, String iconBase64, String classid, String imgurl,
                 String instanceId, String type, String nameColor, Date lastupdatetime) {
        this.name = name;
        this.price = price;
        this.iconBase64 = iconBase64;
        this.classid = classid;
        this.imgurl = imgurl;
        this.instanceId = instanceId;
        this.type = type;
        this.nameColor = nameColor;
        this.lastupdatetime = lastupdatetime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getIconBase64() {
        return this.iconBase64;
    }

    public void setIconBase64(String iconBase64) {
        this.iconBase64 = iconBase64;
    }

    public String getClassid() {
        return this.classid;
    }

    public void setClassid(String classid) {
        this.classid = classid;
    }

    public String getImgurl() {
        return this.imgurl;
    }

    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    public String getInstanceId() {
        return this.instanceId;
    }

    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getNameColor() {
        return this.nameColor;
    }

    public void setNameColor(String nameColor) {
        this.nameColor = nameColor;
    }

    public Date getLastupdatetime() {
        return this.lastupdatetime;
    }

    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

}
