package com.accp.myoa.entity;

// default package
// Generated 2016-4-25 23:13:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Tmp generated by hbm2java
 */
public class Tmp implements java.io.Serializable {

    private String id;
    private String  classid;
    private String  instanceid;
    private String  steamId;
    private String  type;
    private Date    createtime;
    private String  treadable;
    private String  price;
    private String name;
    private String chineseName;
    private String descriptions;
    /**
     * 描述物品种类
     */
    private String desctype;
    /**
     * Setter method for property <tt>desctype</tt>.
     * 
     * @param desctype value to be assigned to property desctype
     */
    public void setDesctype(String desctype) {
        this.desctype = desctype;
    }
    /**
     * Getter method for property <tt>desctype</tt>.
     * 
     * @return property value of desctype
     */
    public String getDesctype() {
        return desctype;
    }
    /**
     * Setter method for property <tt>descriptions</tt>.
     * 
     * @param descriptions value to be assigned to property descriptions
     */
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }
    /**
     * Getter method for property <tt>descriptions</tt>.
     * 
     * @return property value of descriptions
     */
    public String getDescriptions() {
        return descriptions;
    }
    
    /**
     * Setter method for property <tt>chineseName</tt>.
     * 
     * @param chineseName value to be assigned to property chineseName
     */
    public void setChineseName(String chineseName) {
        this.chineseName = chineseName;
    }
    
    /**
     * Getter method for property <tt>chineseName</tt>.
     * 
     * @return property value of chineseName
     */
    public String getChineseName() {
        return chineseName;
    }
    
    /**
     * Setter method for property <tt>name</tt>.
     * 
     * @param name value to be assigned to property name
     */
    public void setName(String name) {
        this.name = name;
    }
    /**
     * Getter method for property <tt>name</tt>.
     * 
     * @return property value of name
     */
    public String getName() {
        return name;
    }

    public Tmp() {
    }

    public Tmp(String classid, String instanceid, String steamId, String type, Date createtime,
               String treadable, String price) {
        this.classid = classid;
        this.instanceid = instanceid;
        this.steamId = steamId;
        this.type = type;
        this.createtime = createtime;
        this.treadable = treadable;
        this.price = price;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getClassid() {
        return this.classid;
    }

    public void setClassid(String classid) {
        this.classid = classid;
    }

    public String getInstanceid() {
        return this.instanceid;
    }

    public void setInstanceid(String instanceid) {
        this.instanceid = instanceid;
    }

    public String getSteamId() {
        return this.steamId;
    }

    public void setSteamId(String steamId) {
        this.steamId = steamId;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Date getCreatetime() {
        return this.createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    public String getTreadable() {
        return this.treadable;
    }

    public void setTreadable(String treadable) {
        this.treadable = treadable;
    }

    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

}
