package com.accp.myoa.entity;

import java.util.List;

// default package
// Generated 2016-4-22 9:33:16 by Hibernate Tools 4.3.1.Final

/**
 * Goods generated by hbm2java
 */
public class tmpGoods implements java.io.Serializable {

    private String id;
    private String  name;
    private String  price;
    private Integer wpnum;
    private String  type;
    private String  steamId;
    private String  iconBase64;
    private Integer tradable;
    private String  classid;
    private String  imgurl;
    private String  instanceId;
    private String  nameColor;
    private String  desctype;
    private List<String> descriptions;
    private String assesstid;
    /**
     * Setter method for property <tt>assesstid</tt>.
     * 
     * @param assesstid value to be assigned to property assesstid
     */
    public void setAssesstid(String assesstid) {
        this.assesstid = assesstid;
    }
    /**
     * Getter method for property <tt>assesstid</tt>.
     * 
     * @return property value of assesstid
     */
    public String getAssesstid() {
        return assesstid;
    }
    
    /**
     * Setter method for property <tt>descriptions</tt>.
     * 
     * @param descriptions value to be assigned to property descriptions
     */
    public void setDescriptions(List<String> descriptions) {
        this.descriptions = descriptions;
    }
    /**
     * Getter method for property <tt>descriptions</tt>.
     * 
     * @return property value of descriptions
     */
    public List<String> getDescriptions() {
        return descriptions;
    }

    /**
     * Setter method for property <tt>desctype</tt>.
     * 
     * @param desctype value to be assigned to property desctype
     */
    public void setDesctype(String desctype) {
        this.desctype = desctype;
    }

    /**
     * Getter method for property <tt>desctype</tt>.
     * 
     * @return property value of desctype
     */
    public String getDesctype() {
        return desctype;
    }

    /**
     * Setter method for property <tt>nameColor</tt>.
     * 
     * @param nameColor value to be assigned to property nameColor
     */
    public void setNameColor(String nameColor) {
        this.nameColor = nameColor;
    }

    /**
     * Getter method for property <tt>nameColor</tt>.
     * 
     * @return property value of nameColor
     */
    public String getNameColor() {
        return nameColor;
    }

    public tmpGoods() {
    }

    public tmpGoods(String name, String price, Integer wpnum, String type, String steamId,
                    String iconBase64, Integer tradable, String classid, String imgurl,
                    String instanceId) {
        this.name = name;
        this.price = price;
        this.wpnum = wpnum;
        this.type = type;
        this.steamId = steamId;
        this.iconBase64 = iconBase64;
        this.tradable = tradable;
        this.classid = classid;
        this.imgurl = imgurl;
        this.instanceId = instanceId;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPrice() {
        return this.price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public Integer getWpnum() {
        return this.wpnum;
    }

    public void setWpnum(Integer wpnum) {
        this.wpnum = wpnum;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSteamId() {
        return this.steamId;
    }

    public void setSteamId(String steamId) {
        this.steamId = steamId;
    }

    public String getIconBase64() {
        return this.iconBase64;
    }

    public void setIconBase64(String iconBase64) {
        this.iconBase64 = iconBase64;
    }

    public Integer getTradable() {
        return this.tradable;
    }

    public void setTradable(Integer tradable) {
        this.tradable = tradable;
    }

    public String getClassid() {
        return this.classid;
    }

    public void setClassid(String classid) {
        this.classid = classid;
    }

    public String getImgurl() {
        return this.imgurl;
    }

    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    public String getInstanceId() {
        return this.instanceId;
    }

    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }

}
